# Generated by Django 5.1 on 2024-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="identificacion",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="identificacion",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
