# Generated by Django 5.1 on 2024-08-13 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0002_alter_cliente_identificacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kardex",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kardex",
                to="comercial.producto",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
