# Generated by Django 5.1 on 2024-08-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0003_alter_kardex_producto_alter_producto_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kardex",
            name="detalle",
            field=models.CharField(
                choices=[
                    ("Compra", "Compra"),
                    ("Venta", "Venta"),
                    ("Baja", "Baja"),
                    ("Alta", "Alta"),
                ],
                default="Compra",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="kardex",
            name="saldo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
