# Generated by Django 5.1 on 2024-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comercial",
            "0004_kardex_detalle_kardex_saldo_alter_kardex_cantidad_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="cantidad",
            new_name="stock",
        ),
        migrations.AddField(
            model_name="adquiscion",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item_adquiscion",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item_venta",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="detalle",
            field=models.CharField(
                choices=[("Compra", "Compra"), ("Venta", "Venta")],
                default="Compra",
                max_length=20,
            ),
        ),
    ]
