# Generated by Django 5.1 on 2024-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0005_rename_cantidad_producto_stock_adquiscion_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo",
            field=models.CharField(default="---", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="presentacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
