# Generated by Django 5.1 on 2024-08-14 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0006_producto_codigo_producto_presentacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("nombre", models.CharField(default="", max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="comercial.marca",
            ),
        ),
    ]
