# Generated by Django 5.1 on 2024-08-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0010_alter_producto_marca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="comercial.marca",
            ),
        ),
    ]
