# Generated by Django 5.1 on 2024-08-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0011_alter_producto_marca"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="marca",
        ),
    ]
