# Generated by Django 5.1 on 2024-08-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0012_remove_producto_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="comercial.marca",
            ),
        ),
        migrations.AlterField(
            model_name="marca",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
