# Generated by Django 5.1 on 2024-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0013_producto_marca_alter_marca_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
