# Generated by Django 5.1 on 2024-08-15 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0014_alter_producto_stock"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adquiscion",
            new_name="Adquisicion",
        ),
        migrations.RenameModel(
            old_name="Item_Adquiscion",
            new_name="Item_Adquisicion",
        ),
        migrations.RenameField(
            model_name="item_adquisicion",
            old_name="adquiscion",
            new_name="adquisicion",
        ),
        migrations.AlterField(
            model_name="producto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="comercial.marca",
            ),
        ),
    ]
