# Generated by Django 5.1 on 2024-08-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0016_alter_adquisicion_fecha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item_adquisicion",
            name="adquisicion",
        ),
        migrations.RemoveField(
            model_name="item_adquisicion",
            name="producto",
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("factura", models.CharField(max_length=50)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item_Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                ("cantidad", models.IntegerField()),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.compra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comercial.producto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Adquisicion",
        ),
        migrations.DeleteModel(
            name="Item_Adquisicion",
        ),
    ]
