# Generated by Django 5.1 on 2024-08-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_remove_item_adquisicion_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='factura',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
