# Generated by Django 5.1 on 2024-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_alter_compra_factura_alter_venta_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
