# Generated by Django 5.1 on 2024-08-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_alter_compra_fecha_alter_kardex_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='detalle',
            new_name='transaccion',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='kardex',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
