# Generated by Django 5.1 on 2024-08-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_rename_detalle_kardex_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
