# Generated by Django 5.1 on 2024-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0022_alter_kardex_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
